version: "3"
services:
  app:
    image: bakeoff
    ports:
      - "5858:5858"
  db:
    image: postgres:10
    environment:
      POSTGRES_DB:
      POSTGRES_PASSWORD: password
    volumes:
      - "./volumes/db:/var/lib/postgresql/data"
