"""drop product fields from pick model

Revision ID: 90412c97879f
Revises: f55c3d740d78
Create Date: 2017-10-09 17:34:14.780534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90412c97879f'
down_revision = 'f55c3d740d78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('picks', 'product_name')
    op.drop_column('picks', 'product_image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('picks', sa.Column('product_image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('picks', sa.Column('product_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
