"""removed assortment model

Revision ID: d6241bd47c3c
Revises: 90412c97879f
Create Date: 2017-10-09 18:35:14.582684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6241bd47c3c'
down_revision = '90412c97879f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('picks_assortment_id_fkey', 'picks', type_='foreignkey')
    op.drop_table('assortment')
    op.add_column('picks', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.add_column('picks', sa.Column('stylist_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'picks', 'customer', ['customer_id'], ['id'])
    op.create_foreign_key(None, 'picks', 'stylist', ['stylist_id'], ['id'])
    op.drop_column('picks', 'assortment_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('picks', sa.Column('assortment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'picks', type_='foreignkey')
    op.drop_constraint(None, 'picks', type_='foreignkey')
    op.create_foreign_key('picks_assortment_id_fkey', 'picks', 'assortment', ['assortment_id'], ['id'])
    op.drop_column('picks', 'stylist_id')
    op.drop_column('picks', 'customer_id')
    op.create_table('assortment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('stylist_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name='assortment_customer_id_fkey'),
    sa.ForeignKeyConstraint(['stylist_id'], ['stylist.id'], name='assortment_stylist_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='assortment_pkey')
    )
    # ### end Alembic commands ###
