"""initial migration

Revision ID: f55c3d740d78
Revises: 
Create Date: 2017-10-09 00:31:26.333918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f55c3d740d78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stylist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assortment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stylist_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['stylist_id'], ['stylist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('picks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ruecom_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('product_image_url', sa.String(length=255), nullable=True),
    sa.Column('assortment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assortment_id'], ['assortment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('picks')
    op.drop_table('assortment')
    op.drop_table('stylist')
    op.drop_table('customer')
    # ### end Alembic commands ###
